# -*- coding: utf-8 -*-
"""Food Item Detection with Yolov7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FhAL3ZO653s33gfA5UxvBCpkCNHdvQTr

# Train YOLOv7 on a wetherspoon food dataset
"""

import os
import subprocess
import torch


# Check NVIDIA GPU (Optional)
subprocess.run('nvidia-smi', shell=True)

# Download YOLOv7 repository and install requirements
subprocess.run('git clone https://github.com/SkalskiP/yolov7.git', shell=True)
os.chdir('yolov7')
subprocess.run('git checkout fix/problems_associated_with_the_latest_versions_of_pytorch_and_numpy', shell=True)
subprocess.run('pip install -r requirements.txt', shell=True)

# Download the Data
#subprocess.run('pip install roboflow', shell=True)
#from roboflow import Roboflow
#rf = Roboflow(api_key="rj9X7b8W62ij7cjtiOO6")
#project = rf.workspace("deep-learning-coursework").project("food-items-detection-sm84b")
#dataset = project.version(7).download("yolov7") #UNaugmented version

# Define the location of your dataset
dataset_location = "/home/sdp360/task2v7/yolov7/Food-Items-detection-7"  # Replace with the actual path

print(torch.cuda.is_available())

# Begin Custom Training
subprocess.run('wget -nc https://github.com/WongKinYiu/yolov7/releases/download/v0.1/yolov7_training.pt', shell=True)
subprocess.run(f"python train.py --batch 16 --epochs 50 --data {dataset_location}/data.yaml --weights 'yolov7_training.pt' --device 0", shell=True)

# Evaluation
subprocess.run(f"python detect.py --weights runs/train/exp/weights/best.pt --conf 0.1 --source {dataset_location}/test/images", shell=True)

# OPTIONAL: Deployment
# Zip to download weights and results locally
subprocess.run('zip -r export.zip runs/detect', shell=True)
subprocess.run('zip -r export.zip runs/train/exp/weights/best.pt', shell=True)
subprocess.run('zip export.zip runs/train/exp/*', shell=True)
